format = """
$directory\
$gcloud\
$git_branch\
$git_status\
$git_state\
$custom\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold blue"
truncation_length = 1

[git_branch]
symbol = " "
style = "bold purple"
truncation_length = 30
format = '[$symbol$branch]($style) '

[time]
disabled = false
time_format = "%T"
utc_time_offset = "+2"
style = "bold purple"
format = '[  $symbol$time]($style) '

[cmd_duration]
format = '[  $duration]($style) '
style = 'bold green'

[gcloud]
disabled = false
format = "[$symbol$project]($style) "
symbol = '󰅟  '
